// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SztuderWiniecki.BikesApp.DAO_EF_SQLite;

#nullable disable

namespace BikesApp.DAO_EF_SQLite.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("SztuderWiniecki.BikesApp.DAO_EF_SQLite.BO.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_producerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("_producerId");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("SztuderWiniecki.BikesApp.DAO_EF_SQLite.BO.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("SztuderWiniecki.BikesApp.DAO_EF_SQLite.BO.Bike", b =>
                {
                    b.HasOne("SztuderWiniecki.BikesApp.DAO_EF_SQLite.BO.Producer", "_producer")
                        .WithMany()
                        .HasForeignKey("_producerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_producer");
                });
#pragma warning restore 612, 618
        }
    }
}
